// Code generated by mockery v2.53.0. DO NOT EDIT.

package mocks

import (
	context "context"
	"time"

	measurements "api_gateway/internal/measurements"

	mock "github.com/stretchr/testify/mock"
)

// MeasurementsReader is an autogenerated mock type for the MeasurementsReader type
type MeasurementsReader struct {
	mock.Mock
}

type MeasurementsReader_Expecter struct {
	mock *mock.Mock
}

func (_m *MeasurementsReader) EXPECT() *MeasurementsReader_Expecter {
	return &MeasurementsReader_Expecter{mock: &_m.Mock}
}

// GetMeasurements provides a mock function with given fields: ctx, assetID, from, to
func (_m *MeasurementsReader) GetMeasurements(ctx context.Context, assetID string, from time.Time, to time.Time) (measurements.MeasurementSeries, error) {
	ret := _m.Called(ctx, assetID, from, to)

	if len(ret) == 0 {
		panic("no return value specified for GetMeasurements")
	}

	var r0 measurements.MeasurementSeries
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, time.Time, time.Time) (measurements.MeasurementSeries, error)); ok {
		return rf(ctx, assetID, from, to)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, time.Time, time.Time) measurements.MeasurementSeries); ok {
		r0 = rf(ctx, assetID, from, to)
	} else {
		r0 = ret.Get(0).(measurements.MeasurementSeries)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, time.Time, time.Time) error); ok {
		r1 = rf(ctx, assetID, from, to)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MeasurementsReader_GetMeasurements_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMeasurements'
type MeasurementsReader_GetMeasurements_Call struct {
	*mock.Call
}

// GetMeasurements is a helper method to define mock.On call
//   - ctx context.Context
//   - assetID string
//   - from time.Time
//   - to time.Time
func (_e *MeasurementsReader_Expecter) GetMeasurements(ctx interface{}, assetID interface{}, from interface{}, to interface{}) *MeasurementsReader_GetMeasurements_Call {
	return &MeasurementsReader_GetMeasurements_Call{Call: _e.mock.On("GetMeasurements", ctx, assetID, from, to)}
}

func (_c *MeasurementsReader_GetMeasurements_Call) Run(run func(ctx context.Context, assetID string, from time.Time, to time.Time)) *MeasurementsReader_GetMeasurements_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(time.Time), args[3].(time.Time))
	})
	return _c
}

func (_c *MeasurementsReader_GetMeasurements_Call) Return(_a0 measurements.MeasurementSeries, _a1 error) *MeasurementsReader_GetMeasurements_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MeasurementsReader_GetMeasurements_Call) RunAndReturn(run func(context.Context, string, time.Time, time.Time) (measurements.MeasurementSeries, error)) *MeasurementsReader_GetMeasurements_Call {
	_c.Call.Return(run)
	return _c
}

// NewMeasurementsReader creates a new instance of MeasurementsReader. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMeasurementsReader(t interface {
	mock.TestingT
	Cleanup(func())
}) *MeasurementsReader {
	mock := &MeasurementsReader{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
