// Code generated by mockery v2.53.0. DO NOT EDIT.

package mocks

import (
	context "context"
	telemetry "stellar/internal/telemetry"

	mock "github.com/stretchr/testify/mock"
)

// TelemetrySource is an autogenerated mock type for the TelemetrySource type
type TelemetrySource struct {
	mock.Mock
}

type TelemetrySource_Expecter struct {
	mock *mock.Mock
}

func (_m *TelemetrySource) EXPECT() *TelemetrySource_Expecter {
	return &TelemetrySource_Expecter{mock: &_m.Mock}
}

// Read provides a mock function with given fields: ctx
func (_m *TelemetrySource) Read(ctx context.Context) (telemetry.TelemetryReading, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Read")
	}

	var r0 telemetry.TelemetryReading
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (telemetry.TelemetryReading, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) telemetry.TelemetryReading); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(telemetry.TelemetryReading)
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TelemetrySource_Read_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Read'
type TelemetrySource_Read_Call struct {
	*mock.Call
}

// Read is a helper method to define mock.On call
//   - ctx context.Context
func (_e *TelemetrySource_Expecter) Read(ctx interface{}) *TelemetrySource_Read_Call {
	return &TelemetrySource_Read_Call{Call: _e.mock.On("Read", ctx)}
}

func (_c *TelemetrySource_Read_Call) Run(run func(ctx context.Context)) *TelemetrySource_Read_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *TelemetrySource_Read_Call) Return(_a0 telemetry.TelemetryReading, _a1 error) *TelemetrySource_Read_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TelemetrySource_Read_Call) RunAndReturn(run func(context.Context) (telemetry.TelemetryReading, error)) *TelemetrySource_Read_Call {
	_c.Call.Return(run)
	return _c
}

// NewTelemetrySource creates a new instance of TelemetrySource. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTelemetrySource(t interface {
	mock.TestingT
	Cleanup(func())
}) *TelemetrySource {
	mock := &TelemetrySource{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
