// Code generated by mockery v2.53.0. DO NOT EDIT.

package mocks

import (
	context "context"
	domain "stellar/internal/telemetry/domain"

	mock "github.com/stretchr/testify/mock"
)

// MeasurementRepository is an autogenerated mock type for the MeasurementRepository type
type MeasurementRepository struct {
	mock.Mock
}

type MeasurementRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MeasurementRepository) EXPECT() *MeasurementRepository_Expecter {
	return &MeasurementRepository_Expecter{mock: &_m.Mock}
}

// Save provides a mock function with given fields: ctx, measurement
func (_m *MeasurementRepository) Save(ctx context.Context, measurement domain.Measurement) error {
	ret := _m.Called(ctx, measurement)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.Measurement) error); ok {
		r0 = rf(ctx, measurement)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MeasurementRepository_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type MeasurementRepository_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - ctx context.Context
//   - measurement domain.Measurement
func (_e *MeasurementRepository_Expecter) Save(ctx interface{}, measurement interface{}) *MeasurementRepository_Save_Call {
	return &MeasurementRepository_Save_Call{Call: _e.mock.On("Save", ctx, measurement)}
}

func (_c *MeasurementRepository_Save_Call) Run(run func(ctx context.Context, measurement domain.Measurement)) *MeasurementRepository_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.Measurement))
	})
	return _c
}

func (_c *MeasurementRepository_Save_Call) Return(_a0 error) *MeasurementRepository_Save_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MeasurementRepository_Save_Call) RunAndReturn(run func(context.Context, domain.Measurement) error) *MeasurementRepository_Save_Call {
	_c.Call.Return(run)
	return _c
}

// NewMeasurementRepository creates a new instance of MeasurementRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMeasurementRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MeasurementRepository {
	mock := &MeasurementRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
